const NEW_MESSAGE = "NEW_MESSAGE"
const NEW_CHAT = "NEW_CHAT"
const DELETE_MESSAGE = "DELETE_MESSAGE"
const DELETE_CHAT = "DELETE_CHAT"
const TYPING = "USER_TYPING"
const USER_CONNECTED = "USER_CONNECTED"
const USER_DISCONNECTED = "USER_DISCONNECTED"
const JOIN_CHAT = "JOIN_CHAT"
const LEAVE_CHAT = "LEAVE_CHAT"
const USER_ONLINE = "USER_ONLINE"
const USER_OFFLINE = "USER_OFFLINE"
const USER_ONLINE_STATUS = "USER_ONLINE_STATUS"

export {
  NEW_MESSAGE,
  NEW_CHAT,
  DELETE_MESSAGE,
  DELETE_CHAT,
  TYPING,
  USER_CONNECTED,
  USER_DISCONNECTED,
  JOIN_CHAT,
  LEAVE_CHAT,
  USER_ONLINE,
  USER_OFFLINE,
  USER_ONLINE_STATUS,
}
